### ISSUE TITLE
布局乱了

### ISSUE THREAD

**Issue by Aoang** [xyxc0673/v2ex-plus#1]
![IMG_20210722_190845](https://user-images.githubusercontent.com/22998599/126630072-25d80f87-63e5-4468-9d1e-a5d536a4ca95.jpg)

**Comment by Aoang** [comment]
Chrome/91.0.4472.164

**Comment by kytrun** [comment]
盲猜是因为你改了 v2ex 首页布局，造成 HTML 元素获取异常。

**Comment by xyxc0673** [comment]
@Aoang 想问下你有用什么自定义 css 吗？因为这个地方是获取首页底部的节点列表。

**Comment by Aoang** [comment]
没有使用任何自定义 CSS，自定义配置中只开启了高精度头像

**Comment by Aoang** [comment]
开了一个没登陆账号的页面对比了下，发现了，设置里面必须打开显示首页节点导航，不然首页是没有节点导航的。
