### ISSUE TITLE
能提供 yarn.lock 和 Podfile.lock 吗？本地安装遇到了一些问题。

### ISSUE THREAD

**Issue by kxxoling** [xyxc0673/v2ex-plus#2]
BTW，有没有在 M1 Mac 上构建过？我在本地尝试解决依赖问题的时候遇到了很多新问题。

**Comment by xyxc0673** [comment]
@kxxoling 我之前是在 intel x86 的机器上跑的，现在换了 M1 的笔记本，刚才试着 yarn start 了一下，发现有些问题，我找个时间看看。

**Comment by xyxc0673** [comment]
@kxxoling 我更新了一下依赖，以及调整了一些配置，现在可以运行在我的 M1 笔记本上了，相关的修改都已经提交了
